name: Update TryHackMe Badge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download TryHackMe badge
        run: |
          mkdir -p assets
          curl -L "https://tryhackme-badges.s3.amazonaws.com/nicocorbeau.png" \
          -o assets/tryhackme-badge.png

      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add assets/tryhackme-badge.png
          git commit -m "Update TryHackMe badge" || echo "No changes"
          git push
